### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by halonazhao** [renjiezhang/CAS-741#10]
https://github.com/renjiezhang/CAS-741/blob/daa7dfc01090cb11c0b47af90cc294f950f21373/Doc/SRS/SRS.tex#L107

I think the units of these symbols may have some problems. I searched whether integer and percentage are valid international units, but I did not find any examples or proofs to say so. From my perspective, at least percentage should not be an unit because it can be considered as a number divide another number and these two numbers should have the same unit. So after division, I think the unit should be 1. Also the price may not be a unit and I think the unit of the price should be a specific currency unit like dollar.

**Comment by renjiezhang** [comment]
you are right, integer should not be the unit. It actually has no units
