### ISSUE TITLE
Description Of Equation Is Not Clear

### ISSUE THREAD

**Issue by halonazhao** [renjiezhang/CAS-741#14]
Some the theoretical models and data definitions did not clearly describe the meaning of variables or constants.

For example,
https://github.com/renjiezhang/CAS-741/blob/daa7dfc01090cb11c0b47af90cc294f950f21373/Doc/SRS/SRS.tex#L329
In this equation, there is no explaination for beta and there is also no description about beta at the beginning in the symbol statement session. There may be a link talking about this equation, but a brief statement about these variables or constants is still needed.

**Comment by renjiezhang** [comment]
OK. I am going to add it
