### ISSUE TITLE
problem statement is ready

### ISSUE THREAD

**Issue by renjiezhang** [renjiezhang/CAS-741#2]
@smiths 
Hello Prof,

Please check the problem statement. It is about the stock prediction using big data and machine learning.

Thanks,

Renjie

**Comment by smiths** [comment]
Hello Renjie.  I approve your problem statement.  My approval is based on the assumption that you already know something about the domain your are studying, Big Data and Spark.  I'm also assuming that you have access to the distributed hardware that you will need.  If any of these assumptions are incorrect, you should let me know and we will reopen this issue to discuss further.

I have also pushed a new version of your problem statement with comments added.
