### ISSUE TITLE
Provide "Correct Results"

### ISSUE THREAD

**Issue by aoananp** [renjiezhang/CAS-741#22]
https://github.com/renjiezhang/CAS-741/blob/ca5dd97ea8f00494d9c5a63fa35f3dac7dd9da46/Doc/TestPlan/TestPlan.tex#L191

One of the main testing activities is to verify that the expected output matches the actual output.
Please provide an expected output/correct results that the verifier can compare with the actual output obtained from the program.

**Comment by smiths** [comment]
How was this issue addressed?

**Comment by renjiezhang** [comment]
Yes, it needs to be more detailed
