### ISSUE TITLE
find issues on VnV

### ISSUE THREAD

**Issue by renjiezhang** [renjiezhang/CAS-741#23]
@smiths 
Hello Prof,

I didn't receive the notice about looking for issues on VnV, since I was busy on the final presentation of CAS 758(we are the first team to present) last week. Can I have 1-2 more days to complete the issue finding?

Thanks
Renjie

**Comment by smiths** [comment]
Hello @renjiezhang.  Yes, you can have up to 2 more days to complete the review.   Therefore, your review is due by Thursday at 11:59 pm.

**Comment by renjiezhang** [comment]
thanks prof.
