### ISSUE TITLE
Implement the interface and functions of the software 

### ISSUE THREAD

**Issue by renjiezhang** [renjiezhang/CAS-741#4]
Hello Prof,

I have a question about the project. As we all have an ideal software design. However, if do we need to build up the interface as designed since we have limit time. For example, there is an interface for user to choose different companies' stocks but I may just do a single company in the sample code. 

Thanks,

Renjie

**Comment by smiths** [comment]
Hello @renjiezhang.  I'm not sure I entirely understand your question, but I'll do my best to answer.  A GUI is not an important part of your project.  I am fine if you focus on the interface as a text based interface.  If you need to make simplifications that is likely fine too.  Document your simplifications, and scope decisions, in your SRS.  That will give us a framework to have these conversations.
