### ISSUE TITLE
about assumption

### ISSUE THREAD

**Issue by renjiezhang** [renjiezhang/CAS-741#5]
Hello Prof,

In my project- Stock price Prediction. It seems like I don't have any assumptions, since the data is the real data from Yahoo Finance.  The prediction is based on the real data. Should I remove the assumptions from SRS?

Thanks,
Renjie

**Comment by smiths** [comment]
Hello Renjie.  You shouldn't remove any sections from the SRS.  If there is nothing to say in a particular section, you still include the heading, but then say that the section is "not applicable" as the content.

Are you sure that there are no assumptions?  The mathematics for stock price prediction must make some assumptions.  Maybe there is something about independence, or a Gaussian distribution, or something?  The data might be real data, but isn't there some modelling taking place?  I strongly believe that the modelling will be making some kind of assumption.

**Comment by renjiezhang** [comment]
Thank for your help Prof,
I am using Support Vector machine as the algorithm. I am not very clear about the assumptions in this case such as independence and Gaussian distribution. How do they affect the prediction? 
Thanks,
Renjie

**Comment by smiths** [comment]
I am not an expert on SVMs, but a quick google search for support vector machine assumptions show several assumptions.  You should include in your document that assumptions that SVM theory is based on.

**Comment by renjiezhang** [comment]
Hello Prof, Yes I found Independent and identically distributed data is a good assumption.  
Thank for your help. 
I am looking for more assumptions

**Comment by smiths** [comment]
Sounds good!
