### ISSUE TITLE
testing tools

### ISSUE THREAD

**Issue by renjiezhang** [renjiezhang/CAS-741#8]
Hello Prof,
I am not sure what testing tools should I use for the integration test. The program reads a data set file and calculate an accuracy rate and an output(go up or go down). There is no standard correct answer for it. Do you have any ideas?

Thanks,
Renjie

**Comment by renjiezhang** [comment]
btw, the program is Python,I could use python unit test framework as the unit testing tool.

**Comment by smiths** [comment]
I spent the lesson on Friday going over ideas.  😄  If you know properties that must be true of a correct answer, you can test for those.  If there is another program that calculates the same thing, you could compare you output to it.  If it is feasible, you could compare your calculations to the results using interval arithmetic.  If there is any way to assume a solution and back calculate the corresponding problem, that would be very helpful.  In the lecture, I called this the method of manufactured solutions.

If none of the above ideas trigger anything, try going over the lecture slides looking for ideas.
